### ISSUE TITLE
Option to create new mailbox is missing for the certain case :

### ISSUE THREAD

**Issue by vaishaliwebkul** [shubhwebkul/mailbox-bundle#4]
**Case** : Create new mailbox 
**Bug** : New Mailbox option is missing 
![download 5](https://user-images.githubusercontent.com/43210406/49358283-1c2f8a00-f6f8-11e8-9a1a-3c636716a3f3.png)

**Comment by shubhwebkul** [comment]
Resolved!

**Comment by vaishaliwebkul** [comment]
Not Fixed, Button is missing while deleting mailbox channel.
